import {
    AlarmClock,
    AlertTriangle,
    ArrowDown01Icon,
    ArrowUp01Icon,
    BarChart3,
    CalendarDays,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUpDown,
    ChevronUp,
    Circle,
    CreditCard,
    Crop,
    CrossIcon,
    DollarSign,
    Download,
    Edit,
    Eye,
    EyeOff,
    FileTerminal,
    Filter,
    Footprints,
    HardHat,
    Image,
    Loader2,
    LogOut,
    Menu,
    MessageSquare,
    PieChart,
    Minus,
    Moon,
    MoreHorizontal,
    MoreVertical,
    
    Package,
    Plus,
    PlusCircle,
    RefreshCw,
    Search,
    Send,
    Settings,
    Shirt,
    ShoppingBag,
    ShoppingCart,
    Sliders,
    SlidersHorizontal,
    SunMedium,
    Trash,
    Twitter,
    UploadCloud,
    User,
    Volume2,
    VolumeX,
    Wallet,
    X,
    HomeIcon,
    Users,
    ChevronLast,
    ChevronFirst,
    PhoneCall,
    type Icon as LucideIcon,
    type LucideProps,
  } from "lucide-react"
  
  export type Icon = LucideIcon
  
  export const Icons = {
    home: HomeIcon,
    sun: SunMedium,
    moon: Moon,
    twitter: Twitter,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    users: Users,
    chevronUpDown: ChevronsUpDown,
    menu: Menu,
    verticalThreeDots: MoreVertical,
    horizontalThreeDots: MoreHorizontal,
    verticalSliders: Sliders,
    horizontalSliders: SlidersHorizontal,
    circle: Circle,
    pie:PieChart,
    check: Check,
    add: Plus,
    addCircle: PlusCircle,
    remove: Minus,
    view: Eye,
    hide: EyeOff,
    trash: Trash,
    edit: Edit,
    crop: Crop,
    reset: RefreshCw,
    send: Send,
    downlaod: Download,
    warning: AlertTriangle,
    search: Search,
    filter: Filter,
    alarm: AlarmClock,
    calendar: CalendarDays,
    user: User,
    terminal: FileTerminal,
    settings: Settings,
    logout: LogOut,
    volumne: Volume2,
    volumneMute: VolumeX,
    message: MessageSquare,
    billing: CreditCard,
    wallet: Wallet,
    dollarSign: DollarSign,
    cart: ShoppingCart,
    product: Package,
    store: ShoppingBag,
    chart: BarChart3,
    upload: UploadCloud,
    placeholder: Image,
    clothing: Shirt,
    shoes: Footprints,
    accessories: HardHat,
    arrowDown: ArrowDown01Icon,
    arrowUp: ArrowUp01Icon,
    chevronLast: ChevronLast,
    chevronFirst: ChevronFirst,
    cross: CrossIcon,
    phoneCall: PhoneCall
}