export default [
    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",

    },
    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",
    
    },
    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",
    
    },
    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",
        
    },    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",

    },
    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",

    },    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",
   
    },
    {
        "agent_avatar": "https://demos.creative-tim.com/notus-nextjs/img/team-3-800x800.jpg",
        "Agt First Name":"Omar",
        "Agt Last Name": "Ayoub",
        "Super First Name": "Mohammad",
        "Super Last Name": "Yahya",
        "Ans SklSet": "E_Channel",
        "In Contact Status": "Active",
        "DN In": "",
        "DN Out": "",

    },
]